{
 "title": "Drill-down Data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Pages",
    "label": "Pages",
    "query": "Main Dashboard, Settings, Drill-down Data, Raw Data"
   },
   {
    "name": "pg_uid",
    "query": "SELECT pg_uid FROM pages WHERE pg_name='$Pages'"
   },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d" },
   {
    "name": "meter_id",
    "label": "Meter ID",
    "query": "SELECT meter_id FROM live_measurements;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "A proof-of-concept dashboard designed for real-time monitoring of energy usage and costs, enabling data-driven decisions to optimize power efficiency in industrial settings.",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; height: 100%;\">\n  <h1 style=\"font-family: 'Inter', sans-serif; font-weight: 600; font-size: 2em; color: #d3d3d3; margin: 0;\">\n    Energy Usage Real-Time Monitoring Dashboard\n  </h1>\n</div>\n"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Supply Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    AVG(v_ab) AS phase_ab,  -- Average of phase AB voltage\r\n    AVG(v_bc) AS phase_bc,  -- Average of phase BC voltage\r\n    AVG(v_ca) AS phase_ca   -- Average of phase CA voltage\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND\r\n     meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    },
    {
     "rawSql": "SELECT max_v\r\nFROM thresholds\r\nORDER BY timestamp DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Voltage Total Harmonic Distortion (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    AVG(thd_v_a) AS phase_a,                -- Average THD for voltage in phase A\r\n    AVG(thd_v_b) AS phase_b,                -- Average THD for voltage in phase B\r\n    AVG(thd_v_c) AS phase_c                 -- Average THD for voltage in phase C\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  },
  {
   "title": "Line Current (A)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    AVG(i_a) AS phase_a,                    -- Average for phase A current\r\n    AVG(i_b) AS phase_b,                    -- Average for phase B current\r\n    AVG(i_c) AS phase_c                     -- Average for phase C current\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  },
  {
   "title": "Current Total Harmonic Distortion (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    AVG(thd_i_a) AS phase_a,                -- Average THD for current in phase A\r\n    AVG(thd_i_b) AS phase_b,                -- Average THD for current in phase B\r\n    AVG(thd_i_c) AS phase_c                 -- Average THD for current in phase C\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    AVG(pf_a) AS phase_a,                   -- Average power factor for phase A\r\n    AVG(pf_b) AS phase_b,                   -- Average power factor for phase B\r\n    AVG(pf_c) AS phase_c                    -- Average power factor for phase C\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  },
  {
   "title": "Total Energy Usage (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    SUM(ABS(kwh)) AS total_kwh\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  },
  {
   "title": "Reactive Power (kVAR)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    AVG(kvar_a) AS phase_a,                 -- Average reactive power for phase A\r\n    AVG(kvar_b) AS phase_b,                 -- Average reactive power for phase B\r\n    AVG(kvar_c) AS phase_c                  -- Average reactive power for phase C\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  },
  {
   "title": "Total Reactive Power (kVAR)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    SUM(kvar_total) AS total_kvar           -- Total reactive power for each hour\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  },
  {
   "title": "Active Power (kW)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    AVG(kw_a) AS phase_a,                   -- Average active power for phase A\r\n    AVG(kw_b) AS phase_b,                   -- Average active power for phase B\r\n    AVG(kw_c) AS phase_c                    -- Average active power for phase C\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  },
  {
   "title": "Total Active Power (kW)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN '${interval}' LIKE '%m' THEN\r\n            date_trunc('minute', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 60\r\n            )  -- Apply minute-based interval (e.g., 5m, 10m, etc.)\r\n        WHEN '${interval}' LIKE '%h' THEN\r\n            date_trunc('hour', timestamp) + INTERVAL '1 second' * (\r\n                CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) * 3600\r\n            )  -- Apply hourly interval (e.g., 6h)\r\n        WHEN '${interval}' LIKE '%d' THEN\r\n            date_trunc('day', timestamp)  -- Apply daily interval (1d)\r\n        WHEN '${interval}' LIKE '%w' THEN\r\n            date_trunc('week', timestamp)  -- Apply weekly interval (7d)\r\n        ELSE\r\n            date_trunc('minute', timestamp)  -- Default to minute interval if no match\r\n    END AS time_interval,\r\n    SUM(kw_total) AS total_kw               -- Total active power for each hour\r\nFROM\r\n    live_measurements\r\nWHERE\r\n    --DATE_TRUNC('month', timestamp) = DATE_TRUNC('month', CURRENT_DATE)  -- Filter for the current month\r\n    --AND \r\n    meter_id = ${meter_id}  -- Filter for selected meter_id\r\n    AND (\r\n        ( '${interval}' LIKE '%m' AND extract(minute from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N minutes\r\n        OR\r\n        ( '${interval}' LIKE '%h' AND extract(hour from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N hours\r\n        OR\r\n        ( '${interval}' LIKE '%d' AND extract(day from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N days\r\n        OR\r\n        ( '${interval}' LIKE '%w' AND extract(week from timestamp)::integer % CAST(SUBSTRING('${interval}' FROM 1 FOR LENGTH('${interval}') - 1) AS INT) = 0 )  -- Select every N weeks\r\n    )\r\nGROUP BY\r\n    time_interval  -- Group by the dynamic time interval\r\nORDER BY\r\n    time_interval;\r\n"
    }
   ]
  }
 ]
}