{
 "title": "Settings",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pg_uid",
    "query": "SELECT pg_uid FROM pages WHERE pg_name = '$Pages'"
   },
   {
    "name": "Pages",
    "label": "Pages",
    "query": "Main Dashboard, Settings, Drill-down Data, Raw Data"
   },
   {
    "name": "User",
    "query": "Admin, Tenant 1, Tenant 2, Tenant 3, Tenant 4, Tenant 5"
   },
   { "name": "meter_id", "label": "Meter ID", "query": "1, 2, 3, 4, 5" },
   {
    "name": "day",
    "label": "Day",
    "query": "sunday, monday, tuesday, wednesday, thursday, friday, saturday"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "A proof-of-concept dashboard designed for real-time monitoring of energy usage and costs, enabling data-driven decisions to optimize power efficiency in industrial settings.",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; height: 100%;\">\n  <h1 style=\"font-family: 'Inter', sans-serif; font-weight: 600; font-size: 2em; color: #d3d3d3; margin: 0;\">\n    Settings Configuration\n  </h1>\n</div>\n"
   }
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Set  Cost Rate and Target Usage",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cost Rate and Target Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    user_id,\r\n    kwh_rate, \r\n    target_usage\r\nFROM \r\n    user_inputs\r\nWHERE \r\n    user_id = '${User}'\r\nORDER BY \r\n    created_at DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Thresholds",
   "type": "table",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    meter_id,\r\n    max_v,\r\n    voltage_imbalance,\r\n    warning_current,\r\n    trip_off_current,\r\n    kvar_max,\r\n    kvar_imbalance,\r\n    kw_max,\r\n    kw_imbalance,\r\n    pf_max AS pf_min,\r\n    vthd_limit,\r\n    ithd_limit\r\nFROM \r\n    thresholds\r\nWHERE \r\n    meter_id = '${meter_id}'  -- Use your dynamic filter variable here\r\nORDER BY \r\n    timestamp DESC\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Set Thresholds",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "frame": {
      "fields": [],
      "meta": {}
     }
    },
    {}
   ]
  },
  {
   "title": "Set Energy Rates & Operation Hour",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Energy Rate & Operation Hour",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    meter_id,\r\n    day,\r\n    peak_rate,\r\n    off_peak_rate,\r\n    peak_hour_start,\r\n    peak_hour_end,\r\n    off_peak_hour_start,\r\n    off_peak_hour_end\r\nFROM poprate\r\nWHERE meter_id = '${meter_id}'\r\nAND day = '${day}'\r\nORDER BY timestamp DESC\r\nLIMIT 1;\r\n"
    }
   ]
  }
 ]
}